# Site settings
title: Data Gallery Blog
email: anna.lukasiak@datagallery.io
description: "Data Gallery Blog, a place to read about our projects and initatives."
github_username: DataGallery
twitter_username: DataGallery

baseurl: "/blog"
url: "http://datagallery.io"
blogurl: "http://datagallery.io/blog"

# Build settings
markdown: kramdown
permalink: pretty
