# Site settings
title: Code for Jersey City Blog
email: anna@codeforjc.org
description: "Code for Jersey City Blog, a place to read about our projects and initatives."
github_username: CodeForJerseyCity
twitter_username: CodeForJC

baseurl: "/blog"
url: "http://codeforjc.org"
blogurl: "http://codeforjc.org/blog"

# Build settings
markdown: kramdown
permalink: pretty
